version: '3'
services:
  bot:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTRES_PORT: 5432
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    restart: always
    depends_on:
      - db